add wave -noupdate -divider {Clean_Beats_Nios2_nios2_processor: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/d_readdatavalid
add wave -noupdate -divider {Clean_Beats_Nios2_nios2_processor: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_status_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_status_reg_u
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_status_reg_eh
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_estatus_reg_u
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_estatus_reg_eh
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_bstatus_reg_u
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_bstatus_reg_eh
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_ienable_reg_irq3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_ipending_reg_irq3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_exception_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_exception_reg_cause
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_pteaddr_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_pteaddr_reg_vpn
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_pteaddr_reg_ptbase
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg_pfn
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg_g
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg_x
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg_w
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg_r
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbacc_reg_c
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_d
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_perm
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_bad
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_dbl
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_pid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_we
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_tlbmisc_reg_way
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_badaddr_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_badaddr_reg_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_pipe_flush_baddr
add wave -noupdate -divider {Clean_Beats_Nios2_nios2_processor: exceptions}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_trap_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_unimp_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_break_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_illegal_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_super_inst_pri9
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_tlb_inst_miss_pri5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_tlb_x_perm_pri6
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_super_inst_addr_pri4
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_super_data_addr_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_misaligned_data_addr_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_misaligned_target_pc_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_hbreak_pri1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_norm_intr_pri3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_break_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_super_inst_pri9
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_super_inst_addr_pri4
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_tlb_inst_miss_pri5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_tlb_x_perm_pri6
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/E_exc_break_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_norm_intr_pri3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_break
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_fast_tlb_miss
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_vpn
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_udtlb_access
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_cancel
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_ignore_exc
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_any
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/M_exc_allowed
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_allowed
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_any 
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_break
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_crst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_ext_intr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_any_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_break_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_active_no_break_no_crst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_active_no_break
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_shadow_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_wr_ea_ba
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/W_debug_mode_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_hbreak_pri1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_norm_intr_pri3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_break_inst_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_super_inst_addr_pri4
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_inst_miss_pri5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_x_perm_pri6
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_super_data_addr_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_miss_pri11
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_r_perm_pri12
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_w_perm_pri12
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_bad_virtual_addr_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_inst_miss_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_data_miss_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_x_perm_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_r_perm_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_w_perm_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_tlb_active
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_misaligned_data_addr_pri10
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Clean_Beats_Nios2_nios2_processor/A_exc_misaligned_target_pc_pri10

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
